/* Generated by ./src/xlat/gen.sh from ./src/xlat/af_tipc_importance.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat af_tipc_importance in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data af_tipc_importance_xdata[] = {
 [TIPC_LOW_IMPORTANCE] = XLAT(TIPC_LOW_IMPORTANCE),
 #define XLAT_VAL_0 ((unsigned) (TIPC_LOW_IMPORTANCE))
 #define XLAT_STR_0 STRINGIFY(TIPC_LOW_IMPORTANCE)
 [TIPC_MEDIUM_IMPORTANCE] = XLAT(TIPC_MEDIUM_IMPORTANCE),
 #define XLAT_VAL_1 ((unsigned) (TIPC_MEDIUM_IMPORTANCE))
 #define XLAT_STR_1 STRINGIFY(TIPC_MEDIUM_IMPORTANCE)
 [TIPC_HIGH_IMPORTANCE] = XLAT(TIPC_HIGH_IMPORTANCE),
 #define XLAT_VAL_2 ((unsigned) (TIPC_HIGH_IMPORTANCE))
 #define XLAT_STR_2 STRINGIFY(TIPC_HIGH_IMPORTANCE)
 [TIPC_CRITICAL_IMPORTANCE] = XLAT(TIPC_CRITICAL_IMPORTANCE),
 #define XLAT_VAL_3 ((unsigned) (TIPC_CRITICAL_IMPORTANCE))
 #define XLAT_STR_3 STRINGIFY(TIPC_CRITICAL_IMPORTANCE)
};
static
const struct xlat af_tipc_importance[1] = { {
 .data = af_tipc_importance_xdata,
 .size = ARRAY_SIZE(af_tipc_importance_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
