/* Generated by ./src/xlat/gen.sh from ./src/xlat/af_tipc_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat af_tipc_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data af_tipc_flags_xdata[] = {
 [TIPC_GROUP_LOOPBACK] = XLAT(TIPC_GROUP_LOOPBACK),
 #define XLAT_VAL_0 ((unsigned) (TIPC_GROUP_LOOPBACK))
 #define XLAT_STR_0 STRINGIFY(TIPC_GROUP_LOOPBACK)
 [TIPC_GROUP_MEMBER_EVTS] = XLAT(TIPC_GROUP_MEMBER_EVTS),
 #define XLAT_VAL_1 ((unsigned) (TIPC_GROUP_MEMBER_EVTS))
 #define XLAT_STR_1 STRINGIFY(TIPC_GROUP_MEMBER_EVTS)
};
static
const struct xlat af_tipc_flags[1] = { {
 .data = af_tipc_flags_xdata,
 .size = ARRAY_SIZE(af_tipc_flags_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
