/* Generated by ./src/xlat/gen.sh from ./src/xlat/af_tipc_types.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat af_tipc_types in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data af_tipc_types_xdata[] = {
 [TIPC_SERVICE_RANGE] = XLAT(TIPC_SERVICE_RANGE),
 #define XLAT_VAL_0 ((unsigned) (TIPC_SERVICE_RANGE))
 #define XLAT_STR_0 STRINGIFY(TIPC_SERVICE_RANGE)
 [TIPC_SERVICE_ADDR] = XLAT(TIPC_SERVICE_ADDR),
 #define XLAT_VAL_1 ((unsigned) (TIPC_SERVICE_ADDR))
 #define XLAT_STR_1 STRINGIFY(TIPC_SERVICE_ADDR)
 [TIPC_SOCKET_ADDR] = XLAT(TIPC_SOCKET_ADDR),
 #define XLAT_VAL_2 ((unsigned) (TIPC_SOCKET_ADDR))
 #define XLAT_STR_2 STRINGIFY(TIPC_SOCKET_ADDR)
};
static
const struct xlat af_tipc_types[1] = { {
 .data = af_tipc_types_xdata,
 .size = ARRAY_SIZE(af_tipc_types_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
