/* Generated by ./src/xlat/gen.sh from ./src/xlat/bpf_file_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(BPF_F_RDONLY) || (defined(HAVE_DECL_BPF_F_RDONLY) && HAVE_DECL_BPF_F_RDONLY)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_RDONLY) == ((1U << 3)), "BPF_F_RDONLY != (1U << 3)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_RDONLY (1U << 3)
#endif
#if defined(BPF_F_WRONLY) || (defined(HAVE_DECL_BPF_F_WRONLY) && HAVE_DECL_BPF_F_WRONLY)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_WRONLY) == ((1U << 4)), "BPF_F_WRONLY != (1U << 4)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_WRONLY (1U << 4)
#endif
#if defined(BPF_F_PATH_FD) || (defined(HAVE_DECL_BPF_F_PATH_FD) && HAVE_DECL_BPF_F_PATH_FD)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_PATH_FD) == ((1U << 14)), "BPF_F_PATH_FD != (1U << 14)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_PATH_FD (1U << 14)
#endif
#if defined(BPF_F_VTYPE_BTF_OBJ_FD) || (defined(HAVE_DECL_BPF_F_VTYPE_BTF_OBJ_FD) && HAVE_DECL_BPF_F_VTYPE_BTF_OBJ_FD)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_VTYPE_BTF_OBJ_FD) == ((1U << 15)), "BPF_F_VTYPE_BTF_OBJ_FD != (1U << 15)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_VTYPE_BTF_OBJ_FD (1U << 15)
#endif
#if defined(BPF_F_TOKEN_FD) || (defined(HAVE_DECL_BPF_F_TOKEN_FD) && HAVE_DECL_BPF_F_TOKEN_FD)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_TOKEN_FD) == ((1U << 16)), "BPF_F_TOKEN_FD != (1U << 16)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_TOKEN_FD (1U << 16)
#endif
#if defined(BPF_F_SEGV_ON_FAULT) || (defined(HAVE_DECL_BPF_F_SEGV_ON_FAULT) && HAVE_DECL_BPF_F_SEGV_ON_FAULT)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_SEGV_ON_FAULT) == ((1U << 17)), "BPF_F_SEGV_ON_FAULT != (1U << 17)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_SEGV_ON_FAULT (1U << 17)
#endif
#if defined(BPF_F_NO_USER_CONV) || (defined(HAVE_DECL_BPF_F_NO_USER_CONV) && HAVE_DECL_BPF_F_NO_USER_CONV)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_NO_USER_CONV) == ((1U << 18)), "BPF_F_NO_USER_CONV != (1U << 18)");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_NO_USER_CONV (1U << 18)
#endif
#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat bpf_file_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data bpf_file_flags_xdata[] = {
 XLAT(BPF_F_RDONLY),
 #define XLAT_VAL_0 ((unsigned) (BPF_F_RDONLY))
 #define XLAT_STR_0 STRINGIFY(BPF_F_RDONLY)
 XLAT(BPF_F_WRONLY),
 #define XLAT_VAL_1 ((unsigned) (BPF_F_WRONLY))
 #define XLAT_STR_1 STRINGIFY(BPF_F_WRONLY)
 XLAT(BPF_F_PATH_FD),
 #define XLAT_VAL_2 ((unsigned) (BPF_F_PATH_FD))
 #define XLAT_STR_2 STRINGIFY(BPF_F_PATH_FD)
 XLAT(BPF_F_VTYPE_BTF_OBJ_FD),
 #define XLAT_VAL_3 ((unsigned) (BPF_F_VTYPE_BTF_OBJ_FD))
 #define XLAT_STR_3 STRINGIFY(BPF_F_VTYPE_BTF_OBJ_FD)
 XLAT(BPF_F_TOKEN_FD),
 #define XLAT_VAL_4 ((unsigned) (BPF_F_TOKEN_FD))
 #define XLAT_STR_4 STRINGIFY(BPF_F_TOKEN_FD)
 XLAT(BPF_F_SEGV_ON_FAULT),
 #define XLAT_VAL_5 ((unsigned) (BPF_F_SEGV_ON_FAULT))
 #define XLAT_STR_5 STRINGIFY(BPF_F_SEGV_ON_FAULT)
 XLAT(BPF_F_NO_USER_CONV),
 #define XLAT_VAL_6 ((unsigned) (BPF_F_NO_USER_CONV))
 #define XLAT_STR_6 STRINGIFY(BPF_F_NO_USER_CONV)
};
static
const struct xlat bpf_file_flags[1] = { {
 .data = bpf_file_flags_xdata,
 .size = ARRAY_SIZE(bpf_file_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
#  ifdef XLAT_VAL_6
  | XLAT_VAL_6
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
#  ifdef XLAT_STR_6
  + sizeof(XLAT_STR_6)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
#  undef XLAT_STR_6
#  undef XLAT_VAL_6
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
