/* Generated by ./src/xlat/gen.sh from ./src/xlat/btrfs_defrag_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

extern const struct xlat btrfs_defrag_flags[];

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data btrfs_defrag_flags_xdata[] = {
 XLAT_TYPE(uint64_t, BTRFS_DEFRAG_RANGE_COMPRESS),
 #define XLAT_VAL_0 ((uint64_t) (BTRFS_DEFRAG_RANGE_COMPRESS))
 #define XLAT_STR_0 STRINGIFY(BTRFS_DEFRAG_RANGE_COMPRESS)
 XLAT_TYPE(uint64_t, BTRFS_DEFRAG_RANGE_START_IO),
 #define XLAT_VAL_1 ((uint64_t) (BTRFS_DEFRAG_RANGE_START_IO))
 #define XLAT_STR_1 STRINGIFY(BTRFS_DEFRAG_RANGE_START_IO)
 XLAT_TYPE(uint64_t, BTRFS_DEFRAG_RANGE_COMPRESS_LEVEL),
 #define XLAT_VAL_2 ((uint64_t) (BTRFS_DEFRAG_RANGE_COMPRESS_LEVEL))
 #define XLAT_STR_2 STRINGIFY(BTRFS_DEFRAG_RANGE_COMPRESS_LEVEL)
 XLAT_TYPE(uint64_t, BTRFS_DEFRAG_RANGE_NOCOMPRESS),
 #define XLAT_VAL_3 ((uint64_t) (BTRFS_DEFRAG_RANGE_NOCOMPRESS))
 #define XLAT_STR_3 STRINGIFY(BTRFS_DEFRAG_RANGE_NOCOMPRESS)
};
#  if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
#  endif
const struct xlat btrfs_defrag_flags[1] = { {
 .data = btrfs_defrag_flags_xdata,
 .size = ARRAY_SIZE(btrfs_defrag_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
