/* Generated by ./src/xlat/gen.sh from ./src/xlat/clone3_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat clone3_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data clone3_flags_xdata[] = {
 XLAT_TYPE(uint64_t, CLONE_NEWTIME),
 #define XLAT_VAL_0 ((uint64_t) (CLONE_NEWTIME))
 #define XLAT_STR_0 STRINGIFY(CLONE_NEWTIME)
 XLAT_TYPE(uint64_t, CLONE_CLEAR_SIGHAND),
 #define XLAT_VAL_1 ((uint64_t) (CLONE_CLEAR_SIGHAND))
 #define XLAT_STR_1 STRINGIFY(CLONE_CLEAR_SIGHAND)
 XLAT_TYPE(uint64_t, CLONE_INTO_CGROUP),
 #define XLAT_VAL_2 ((uint64_t) (CLONE_INTO_CGROUP))
 #define XLAT_STR_2 STRINGIFY(CLONE_INTO_CGROUP)
 XLAT_TYPE(uint64_t, CLONE_AUTOREAP),
 #define XLAT_VAL_3 ((uint64_t) (CLONE_AUTOREAP))
 #define XLAT_STR_3 STRINGIFY(CLONE_AUTOREAP)
 XLAT_TYPE(uint64_t, CLONE_NNP),
 #define XLAT_VAL_4 ((uint64_t) (CLONE_NNP))
 #define XLAT_STR_4 STRINGIFY(CLONE_NNP)
 XLAT_TYPE(uint64_t, CLONE_PIDFD_AUTOKILL),
 #define XLAT_VAL_5 ((uint64_t) (CLONE_PIDFD_AUTOKILL))
 #define XLAT_STR_5 STRINGIFY(CLONE_PIDFD_AUTOKILL)
 XLAT_TYPE(uint64_t, CLONE_EMPTY_MNTNS),
 #define XLAT_VAL_6 ((uint64_t) (CLONE_EMPTY_MNTNS))
 #define XLAT_STR_6 STRINGIFY(CLONE_EMPTY_MNTNS)
};
static
const struct xlat clone3_flags[1] = { {
 .data = clone3_flags_xdata,
 .size = ARRAY_SIZE(clone3_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
#  ifdef XLAT_VAL_6
  | XLAT_VAL_6
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
#  ifdef XLAT_STR_6
  + sizeof(XLAT_STR_6)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
#  undef XLAT_STR_6
#  undef XLAT_VAL_6
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
