/* Generated by ./src/xlat/gen.sh from ./src/xlat/crypto_nl_attrs.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat crypto_nl_attrs in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data crypto_nl_attrs_xdata[] = {
 [CRYPTOCFGA_UNSPEC] = XLAT(CRYPTOCFGA_UNSPEC),
 #define XLAT_VAL_0 ((unsigned) (CRYPTOCFGA_UNSPEC))
 #define XLAT_STR_0 STRINGIFY(CRYPTOCFGA_UNSPEC)
 [CRYPTOCFGA_PRIORITY_VAL] = XLAT(CRYPTOCFGA_PRIORITY_VAL),
 #define XLAT_VAL_1 ((unsigned) (CRYPTOCFGA_PRIORITY_VAL))
 #define XLAT_STR_1 STRINGIFY(CRYPTOCFGA_PRIORITY_VAL)
 [CRYPTOCFGA_REPORT_LARVAL] = XLAT(CRYPTOCFGA_REPORT_LARVAL),
 #define XLAT_VAL_2 ((unsigned) (CRYPTOCFGA_REPORT_LARVAL))
 #define XLAT_STR_2 STRINGIFY(CRYPTOCFGA_REPORT_LARVAL)
 [CRYPTOCFGA_REPORT_HASH] = XLAT(CRYPTOCFGA_REPORT_HASH),
 #define XLAT_VAL_3 ((unsigned) (CRYPTOCFGA_REPORT_HASH))
 #define XLAT_STR_3 STRINGIFY(CRYPTOCFGA_REPORT_HASH)
 [CRYPTOCFGA_REPORT_BLKCIPHER] = XLAT(CRYPTOCFGA_REPORT_BLKCIPHER),
 #define XLAT_VAL_4 ((unsigned) (CRYPTOCFGA_REPORT_BLKCIPHER))
 #define XLAT_STR_4 STRINGIFY(CRYPTOCFGA_REPORT_BLKCIPHER)
 [CRYPTOCFGA_REPORT_AEAD] = XLAT(CRYPTOCFGA_REPORT_AEAD),
 #define XLAT_VAL_5 ((unsigned) (CRYPTOCFGA_REPORT_AEAD))
 #define XLAT_STR_5 STRINGIFY(CRYPTOCFGA_REPORT_AEAD)
 [CRYPTOCFGA_REPORT_COMPRESS] = XLAT(CRYPTOCFGA_REPORT_COMPRESS),
 #define XLAT_VAL_6 ((unsigned) (CRYPTOCFGA_REPORT_COMPRESS))
 #define XLAT_STR_6 STRINGIFY(CRYPTOCFGA_REPORT_COMPRESS)
 [CRYPTOCFGA_REPORT_RNG] = XLAT(CRYPTOCFGA_REPORT_RNG),
 #define XLAT_VAL_7 ((unsigned) (CRYPTOCFGA_REPORT_RNG))
 #define XLAT_STR_7 STRINGIFY(CRYPTOCFGA_REPORT_RNG)
 [CRYPTOCFGA_REPORT_CIPHER] = XLAT(CRYPTOCFGA_REPORT_CIPHER),
 #define XLAT_VAL_8 ((unsigned) (CRYPTOCFGA_REPORT_CIPHER))
 #define XLAT_STR_8 STRINGIFY(CRYPTOCFGA_REPORT_CIPHER)
 [CRYPTOCFGA_REPORT_AKCIPHER] = XLAT(CRYPTOCFGA_REPORT_AKCIPHER),
 #define XLAT_VAL_9 ((unsigned) (CRYPTOCFGA_REPORT_AKCIPHER))
 #define XLAT_STR_9 STRINGIFY(CRYPTOCFGA_REPORT_AKCIPHER)
 [CRYPTOCFGA_REPORT_KPP] = XLAT(CRYPTOCFGA_REPORT_KPP),
 #define XLAT_VAL_10 ((unsigned) (CRYPTOCFGA_REPORT_KPP))
 #define XLAT_STR_10 STRINGIFY(CRYPTOCFGA_REPORT_KPP)
 [CRYPTOCFGA_REPORT_ACOMP] = XLAT(CRYPTOCFGA_REPORT_ACOMP),
 #define XLAT_VAL_11 ((unsigned) (CRYPTOCFGA_REPORT_ACOMP))
 #define XLAT_STR_11 STRINGIFY(CRYPTOCFGA_REPORT_ACOMP)
 [CRYPTOCFGA_STAT_LARVAL] = XLAT(CRYPTOCFGA_STAT_LARVAL),
 #define XLAT_VAL_12 ((unsigned) (CRYPTOCFGA_STAT_LARVAL))
 #define XLAT_STR_12 STRINGIFY(CRYPTOCFGA_STAT_LARVAL)
 [CRYPTOCFGA_STAT_HASH] = XLAT(CRYPTOCFGA_STAT_HASH),
 #define XLAT_VAL_13 ((unsigned) (CRYPTOCFGA_STAT_HASH))
 #define XLAT_STR_13 STRINGIFY(CRYPTOCFGA_STAT_HASH)
 [CRYPTOCFGA_STAT_BLKCIPHER] = XLAT(CRYPTOCFGA_STAT_BLKCIPHER),
 #define XLAT_VAL_14 ((unsigned) (CRYPTOCFGA_STAT_BLKCIPHER))
 #define XLAT_STR_14 STRINGIFY(CRYPTOCFGA_STAT_BLKCIPHER)
 [CRYPTOCFGA_STAT_AEAD] = XLAT(CRYPTOCFGA_STAT_AEAD),
 #define XLAT_VAL_15 ((unsigned) (CRYPTOCFGA_STAT_AEAD))
 #define XLAT_STR_15 STRINGIFY(CRYPTOCFGA_STAT_AEAD)
 [CRYPTOCFGA_STAT_COMPRESS] = XLAT(CRYPTOCFGA_STAT_COMPRESS),
 #define XLAT_VAL_16 ((unsigned) (CRYPTOCFGA_STAT_COMPRESS))
 #define XLAT_STR_16 STRINGIFY(CRYPTOCFGA_STAT_COMPRESS)
 [CRYPTOCFGA_STAT_RNG] = XLAT(CRYPTOCFGA_STAT_RNG),
 #define XLAT_VAL_17 ((unsigned) (CRYPTOCFGA_STAT_RNG))
 #define XLAT_STR_17 STRINGIFY(CRYPTOCFGA_STAT_RNG)
 [CRYPTOCFGA_STAT_CIPHER] = XLAT(CRYPTOCFGA_STAT_CIPHER),
 #define XLAT_VAL_18 ((unsigned) (CRYPTOCFGA_STAT_CIPHER))
 #define XLAT_STR_18 STRINGIFY(CRYPTOCFGA_STAT_CIPHER)
 [CRYPTOCFGA_STAT_AKCIPHER] = XLAT(CRYPTOCFGA_STAT_AKCIPHER),
 #define XLAT_VAL_19 ((unsigned) (CRYPTOCFGA_STAT_AKCIPHER))
 #define XLAT_STR_19 STRINGIFY(CRYPTOCFGA_STAT_AKCIPHER)
 [CRYPTOCFGA_STAT_KPP] = XLAT(CRYPTOCFGA_STAT_KPP),
 #define XLAT_VAL_20 ((unsigned) (CRYPTOCFGA_STAT_KPP))
 #define XLAT_STR_20 STRINGIFY(CRYPTOCFGA_STAT_KPP)
 [CRYPTOCFGA_STAT_ACOMP] = XLAT(CRYPTOCFGA_STAT_ACOMP),
 #define XLAT_VAL_21 ((unsigned) (CRYPTOCFGA_STAT_ACOMP))
 #define XLAT_STR_21 STRINGIFY(CRYPTOCFGA_STAT_ACOMP)
 [CRYPTOCFGA_REPORT_SIG] = XLAT(CRYPTOCFGA_REPORT_SIG),
 #define XLAT_VAL_22 ((unsigned) (CRYPTOCFGA_REPORT_SIG))
 #define XLAT_STR_22 STRINGIFY(CRYPTOCFGA_REPORT_SIG)
};
static
const struct xlat crypto_nl_attrs[1] = { {
 .data = crypto_nl_attrs_xdata,
 .size = ARRAY_SIZE(crypto_nl_attrs_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
#  ifdef XLAT_VAL_6
  | XLAT_VAL_6
#  endif
#  ifdef XLAT_VAL_7
  | XLAT_VAL_7
#  endif
#  ifdef XLAT_VAL_8
  | XLAT_VAL_8
#  endif
#  ifdef XLAT_VAL_9
  | XLAT_VAL_9
#  endif
#  ifdef XLAT_VAL_10
  | XLAT_VAL_10
#  endif
#  ifdef XLAT_VAL_11
  | XLAT_VAL_11
#  endif
#  ifdef XLAT_VAL_12
  | XLAT_VAL_12
#  endif
#  ifdef XLAT_VAL_13
  | XLAT_VAL_13
#  endif
#  ifdef XLAT_VAL_14
  | XLAT_VAL_14
#  endif
#  ifdef XLAT_VAL_15
  | XLAT_VAL_15
#  endif
#  ifdef XLAT_VAL_16
  | XLAT_VAL_16
#  endif
#  ifdef XLAT_VAL_17
  | XLAT_VAL_17
#  endif
#  ifdef XLAT_VAL_18
  | XLAT_VAL_18
#  endif
#  ifdef XLAT_VAL_19
  | XLAT_VAL_19
#  endif
#  ifdef XLAT_VAL_20
  | XLAT_VAL_20
#  endif
#  ifdef XLAT_VAL_21
  | XLAT_VAL_21
#  endif
#  ifdef XLAT_VAL_22
  | XLAT_VAL_22
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
#  ifdef XLAT_STR_6
  + sizeof(XLAT_STR_6)
#  endif
#  ifdef XLAT_STR_7
  + sizeof(XLAT_STR_7)
#  endif
#  ifdef XLAT_STR_8
  + sizeof(XLAT_STR_8)
#  endif
#  ifdef XLAT_STR_9
  + sizeof(XLAT_STR_9)
#  endif
#  ifdef XLAT_STR_10
  + sizeof(XLAT_STR_10)
#  endif
#  ifdef XLAT_STR_11
  + sizeof(XLAT_STR_11)
#  endif
#  ifdef XLAT_STR_12
  + sizeof(XLAT_STR_12)
#  endif
#  ifdef XLAT_STR_13
  + sizeof(XLAT_STR_13)
#  endif
#  ifdef XLAT_STR_14
  + sizeof(XLAT_STR_14)
#  endif
#  ifdef XLAT_STR_15
  + sizeof(XLAT_STR_15)
#  endif
#  ifdef XLAT_STR_16
  + sizeof(XLAT_STR_16)
#  endif
#  ifdef XLAT_STR_17
  + sizeof(XLAT_STR_17)
#  endif
#  ifdef XLAT_STR_18
  + sizeof(XLAT_STR_18)
#  endif
#  ifdef XLAT_STR_19
  + sizeof(XLAT_STR_19)
#  endif
#  ifdef XLAT_STR_20
  + sizeof(XLAT_STR_20)
#  endif
#  ifdef XLAT_STR_21
  + sizeof(XLAT_STR_21)
#  endif
#  ifdef XLAT_STR_22
  + sizeof(XLAT_STR_22)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
#  undef XLAT_STR_6
#  undef XLAT_VAL_6
#  undef XLAT_STR_7
#  undef XLAT_VAL_7
#  undef XLAT_STR_8
#  undef XLAT_VAL_8
#  undef XLAT_STR_9
#  undef XLAT_VAL_9
#  undef XLAT_STR_10
#  undef XLAT_VAL_10
#  undef XLAT_STR_11
#  undef XLAT_VAL_11
#  undef XLAT_STR_12
#  undef XLAT_VAL_12
#  undef XLAT_STR_13
#  undef XLAT_VAL_13
#  undef XLAT_STR_14
#  undef XLAT_VAL_14
#  undef XLAT_STR_15
#  undef XLAT_VAL_15
#  undef XLAT_STR_16
#  undef XLAT_VAL_16
#  undef XLAT_STR_17
#  undef XLAT_VAL_17
#  undef XLAT_STR_18
#  undef XLAT_VAL_18
#  undef XLAT_STR_19
#  undef XLAT_VAL_19
#  undef XLAT_STR_20
#  undef XLAT_VAL_20
#  undef XLAT_STR_21
#  undef XLAT_VAL_21
#  undef XLAT_STR_22
#  undef XLAT_VAL_22
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
