/* Generated by ./src/xlat/gen.sh from ./src/xlat/fs_shutdown_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat fs_shutdown_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data fs_shutdown_flags_xdata[] = {
 [FS_SHUTDOWN_FLAGS_DEFAULT] = XLAT(FS_SHUTDOWN_FLAGS_DEFAULT),
 #define XLAT_VAL_0 ((unsigned) (FS_SHUTDOWN_FLAGS_DEFAULT))
 #define XLAT_STR_0 STRINGIFY(FS_SHUTDOWN_FLAGS_DEFAULT)
 [FS_SHUTDOWN_FLAGS_LOGFLUSH] = XLAT(FS_SHUTDOWN_FLAGS_LOGFLUSH),
 #define XLAT_VAL_1 ((unsigned) (FS_SHUTDOWN_FLAGS_LOGFLUSH))
 #define XLAT_STR_1 STRINGIFY(FS_SHUTDOWN_FLAGS_LOGFLUSH)
 [FS_SHUTDOWN_FLAGS_NOLOGFLUSH] = XLAT(FS_SHUTDOWN_FLAGS_NOLOGFLUSH),
 #define XLAT_VAL_2 ((unsigned) (FS_SHUTDOWN_FLAGS_NOLOGFLUSH))
 #define XLAT_STR_2 STRINGIFY(FS_SHUTDOWN_FLAGS_NOLOGFLUSH)
};
static
const struct xlat fs_shutdown_flags[1] = { {
 .data = fs_shutdown_flags_xdata,
 .size = ARRAY_SIZE(fs_shutdown_flags_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
