/* Generated by ./src/xlat/gen.sh from ./src/xlat/genl_taskstats_cmd.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat genl_taskstats_cmd in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data genl_taskstats_cmd_xdata[] = {

 [TASKSTATS_CMD_UNSPEC] = XLAT(TASKSTATS_CMD_UNSPEC),
 #define XLAT_VAL_0 ((unsigned) (TASKSTATS_CMD_UNSPEC))
 #define XLAT_STR_0 STRINGIFY(TASKSTATS_CMD_UNSPEC)
 [TASKSTATS_CMD_GET] = XLAT(TASKSTATS_CMD_GET),
 #define XLAT_VAL_1 ((unsigned) (TASKSTATS_CMD_GET))
 #define XLAT_STR_1 STRINGIFY(TASKSTATS_CMD_GET)
 [TASKSTATS_CMD_NEW] = XLAT(TASKSTATS_CMD_NEW),
 #define XLAT_VAL_2 ((unsigned) (TASKSTATS_CMD_NEW))
 #define XLAT_STR_2 STRINGIFY(TASKSTATS_CMD_NEW)

 [CGROUPSTATS_CMD_UNSPEC] = XLAT(CGROUPSTATS_CMD_UNSPEC),
 #define XLAT_VAL_3 ((unsigned) (CGROUPSTATS_CMD_UNSPEC))
 #define XLAT_STR_3 STRINGIFY(CGROUPSTATS_CMD_UNSPEC)
 [CGROUPSTATS_CMD_GET] = XLAT(CGROUPSTATS_CMD_GET),
 #define XLAT_VAL_4 ((unsigned) (CGROUPSTATS_CMD_GET))
 #define XLAT_STR_4 STRINGIFY(CGROUPSTATS_CMD_GET)
 [CGROUPSTATS_CMD_NEW] = XLAT(CGROUPSTATS_CMD_NEW),
 #define XLAT_VAL_5 ((unsigned) (CGROUPSTATS_CMD_NEW))
 #define XLAT_STR_5 STRINGIFY(CGROUPSTATS_CMD_NEW)
};
static
const struct xlat genl_taskstats_cmd[1] = { {
 .data = genl_taskstats_cmd_xdata,
 .size = ARRAY_SIZE(genl_taskstats_cmd_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
