/* Generated by ./src/xlat/gen.sh from ./src/xlat/genl_thermal_cmd.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat genl_thermal_cmd in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data genl_thermal_cmd_xdata[] = {

 [THERMAL_GENL_CMD_UNSPEC] = XLAT(THERMAL_GENL_CMD_UNSPEC),
 #define XLAT_VAL_0 ((unsigned) (THERMAL_GENL_CMD_UNSPEC))
 #define XLAT_STR_0 STRINGIFY(THERMAL_GENL_CMD_UNSPEC)
 [THERMAL_GENL_CMD_TZ_GET_ID] = XLAT(THERMAL_GENL_CMD_TZ_GET_ID),
 #define XLAT_VAL_1 ((unsigned) (THERMAL_GENL_CMD_TZ_GET_ID))
 #define XLAT_STR_1 STRINGIFY(THERMAL_GENL_CMD_TZ_GET_ID)
 [THERMAL_GENL_CMD_TZ_GET_TRIP] = XLAT(THERMAL_GENL_CMD_TZ_GET_TRIP),
 #define XLAT_VAL_2 ((unsigned) (THERMAL_GENL_CMD_TZ_GET_TRIP))
 #define XLAT_STR_2 STRINGIFY(THERMAL_GENL_CMD_TZ_GET_TRIP)
 [THERMAL_GENL_CMD_TZ_GET_TEMP] = XLAT(THERMAL_GENL_CMD_TZ_GET_TEMP),
 #define XLAT_VAL_3 ((unsigned) (THERMAL_GENL_CMD_TZ_GET_TEMP))
 #define XLAT_STR_3 STRINGIFY(THERMAL_GENL_CMD_TZ_GET_TEMP)
 [THERMAL_GENL_CMD_TZ_GET_GOV] = XLAT(THERMAL_GENL_CMD_TZ_GET_GOV),
 #define XLAT_VAL_4 ((unsigned) (THERMAL_GENL_CMD_TZ_GET_GOV))
 #define XLAT_STR_4 STRINGIFY(THERMAL_GENL_CMD_TZ_GET_GOV)
 [THERMAL_GENL_CMD_TZ_GET_MODE] = XLAT(THERMAL_GENL_CMD_TZ_GET_MODE),
 #define XLAT_VAL_5 ((unsigned) (THERMAL_GENL_CMD_TZ_GET_MODE))
 #define XLAT_STR_5 STRINGIFY(THERMAL_GENL_CMD_TZ_GET_MODE)
 [THERMAL_GENL_CMD_CDEV_GET] = XLAT(THERMAL_GENL_CMD_CDEV_GET),
 #define XLAT_VAL_6 ((unsigned) (THERMAL_GENL_CMD_CDEV_GET))
 #define XLAT_STR_6 STRINGIFY(THERMAL_GENL_CMD_CDEV_GET)
};
static
const struct xlat genl_thermal_cmd[1] = { {
 .data = genl_thermal_cmd_xdata,
 .size = ARRAY_SIZE(genl_thermal_cmd_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
#  ifdef XLAT_VAL_6
  | XLAT_VAL_6
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
#  ifdef XLAT_STR_6
  + sizeof(XLAT_STR_6)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
#  undef XLAT_STR_6
#  undef XLAT_VAL_6
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
