/* Generated by ./src/xlat/gen.sh from ./src/xlat/hdio_ide_nice.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat hdio_ide_nice in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data hdio_ide_nice_xdata[] = {
#if defined(IDE_NICE_DSC_OVERLAP) || (defined(HAVE_DECL_IDE_NICE_DSC_OVERLAP) && HAVE_DECL_IDE_NICE_DSC_OVERLAP)
  XLAT_PAIR(1ULL<<IDE_NICE_DSC_OVERLAP, "1<<IDE_NICE_DSC_OVERLAP"),
 #define XLAT_VAL_0 ((unsigned) (1ULL<<IDE_NICE_DSC_OVERLAP))
 #define XLAT_STR_0 "1<<IDE_NICE_DSC_OVERLAP"
#endif
#if defined(IDE_NICE_ATAPI_OVERLAP) || (defined(HAVE_DECL_IDE_NICE_ATAPI_OVERLAP) && HAVE_DECL_IDE_NICE_ATAPI_OVERLAP)
  XLAT_PAIR(1ULL<<IDE_NICE_ATAPI_OVERLAP, "1<<IDE_NICE_ATAPI_OVERLAP"),
 #define XLAT_VAL_1 ((unsigned) (1ULL<<IDE_NICE_ATAPI_OVERLAP))
 #define XLAT_STR_1 "1<<IDE_NICE_ATAPI_OVERLAP"
#endif
#if defined(IDE_NICE_1) || (defined(HAVE_DECL_IDE_NICE_1) && HAVE_DECL_IDE_NICE_1)
  XLAT_PAIR(1ULL<<IDE_NICE_1, "1<<IDE_NICE_1"),
 #define XLAT_VAL_2 ((unsigned) (1ULL<<IDE_NICE_1))
 #define XLAT_STR_2 "1<<IDE_NICE_1"
#endif
#if defined(IDE_NICE_0) || (defined(HAVE_DECL_IDE_NICE_0) && HAVE_DECL_IDE_NICE_0)
  XLAT_PAIR(1ULL<<IDE_NICE_0, "1<<IDE_NICE_0"),
 #define XLAT_VAL_3 ((unsigned) (1ULL<<IDE_NICE_0))
 #define XLAT_STR_3 "1<<IDE_NICE_0"
#endif
#if defined(IDE_NICE_2) || (defined(HAVE_DECL_IDE_NICE_2) && HAVE_DECL_IDE_NICE_2)
  XLAT_PAIR(1ULL<<IDE_NICE_2, "1<<IDE_NICE_2"),
 #define XLAT_VAL_4 ((unsigned) (1ULL<<IDE_NICE_2))
 #define XLAT_STR_4 "1<<IDE_NICE_2"
#endif
};
static
const struct xlat hdio_ide_nice[1] = { {
 .data = hdio_ide_nice_xdata,
 .size = ARRAY_SIZE(hdio_ide_nice_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
