/* Generated by ./src/xlat/gen.sh from ./src/xlat/ifa_protocols.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat ifa_protocols in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data ifa_protocols_xdata[] = {
 [IFAPROT_UNSPEC] = XLAT(IFAPROT_UNSPEC),
 #define XLAT_VAL_0 ((unsigned) (IFAPROT_UNSPEC))
 #define XLAT_STR_0 STRINGIFY(IFAPROT_UNSPEC)
 [IFAPROT_KERNEL_LO] = XLAT(IFAPROT_KERNEL_LO),
 #define XLAT_VAL_1 ((unsigned) (IFAPROT_KERNEL_LO))
 #define XLAT_STR_1 STRINGIFY(IFAPROT_KERNEL_LO)
 [IFAPROT_KERNEL_RA] = XLAT(IFAPROT_KERNEL_RA),
 #define XLAT_VAL_2 ((unsigned) (IFAPROT_KERNEL_RA))
 #define XLAT_STR_2 STRINGIFY(IFAPROT_KERNEL_RA)
 [IFAPROT_KERNEL_LL] = XLAT(IFAPROT_KERNEL_LL),
 #define XLAT_VAL_3 ((unsigned) (IFAPROT_KERNEL_LL))
 #define XLAT_STR_3 STRINGIFY(IFAPROT_KERNEL_LL)
};
static
const struct xlat ifa_protocols[1] = { {
 .data = ifa_protocols_xdata,
 .size = ARRAY_SIZE(ifa_protocols_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
