/* Generated by ./src/xlat/gen.sh from ./src/xlat/ifa_lifetimes.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(INFINITY_LIFE_TIME) || (defined(HAVE_DECL_INFINITY_LIFE_TIME) && HAVE_DECL_INFINITY_LIFE_TIME)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((INFINITY_LIFE_TIME) == (0xFFFFFFFFU), "INFINITY_LIFE_TIME != 0xFFFFFFFFU");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define INFINITY_LIFE_TIME 0xFFFFFFFFU
#endif
#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat ifa_lifetimes in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data ifa_lifetimes_xdata[] = {
 XLAT(INFINITY_LIFE_TIME),
 #define XLAT_VAL_0 ((unsigned) (INFINITY_LIFE_TIME))
 #define XLAT_STR_0 STRINGIFY(INFINITY_LIFE_TIME)
};
static
const struct xlat ifa_lifetimes[1] = { {
 .data = ifa_lifetimes_xdata,
 .size = ARRAY_SIZE(ifa_lifetimes_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
