/* Generated by ./src/xlat/gen.sh from ./src/xlat/landlock_ruleset_access_net.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat landlock_ruleset_access_net in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data landlock_ruleset_access_net_xdata[] = {
 XLAT(LANDLOCK_ACCESS_NET_BIND_TCP),
 #define XLAT_VAL_0 ((unsigned) (LANDLOCK_ACCESS_NET_BIND_TCP))
 #define XLAT_STR_0 STRINGIFY(LANDLOCK_ACCESS_NET_BIND_TCP)
 XLAT(LANDLOCK_ACCESS_NET_CONNECT_TCP),
 #define XLAT_VAL_1 ((unsigned) (LANDLOCK_ACCESS_NET_CONNECT_TCP))
 #define XLAT_STR_1 STRINGIFY(LANDLOCK_ACCESS_NET_CONNECT_TCP)
 XLAT(LANDLOCK_ACCESS_NET_BIND_UDP),
 #define XLAT_VAL_2 ((unsigned) (LANDLOCK_ACCESS_NET_BIND_UDP))
 #define XLAT_STR_2 STRINGIFY(LANDLOCK_ACCESS_NET_BIND_UDP)
 XLAT(LANDLOCK_ACCESS_NET_CONNECT_SEND_UDP),
 #define XLAT_VAL_3 ((unsigned) (LANDLOCK_ACCESS_NET_CONNECT_SEND_UDP))
 #define XLAT_STR_3 STRINGIFY(LANDLOCK_ACCESS_NET_CONNECT_SEND_UDP)
};
static
const struct xlat landlock_ruleset_access_net[1] = { {
 .data = landlock_ruleset_access_net_xdata,
 .size = ARRAY_SIZE(landlock_ruleset_access_net_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
