/* Generated by ./src/xlat/gen.sh from ./src/xlat/landlock_restrict_self_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat landlock_restrict_self_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data landlock_restrict_self_flags_xdata[] = {
 XLAT(LANDLOCK_RESTRICT_SELF_LOG_SAME_EXEC_OFF),
 #define XLAT_VAL_0 ((unsigned) (LANDLOCK_RESTRICT_SELF_LOG_SAME_EXEC_OFF))
 #define XLAT_STR_0 STRINGIFY(LANDLOCK_RESTRICT_SELF_LOG_SAME_EXEC_OFF)
 XLAT(LANDLOCK_RESTRICT_SELF_LOG_NEW_EXEC_ON),
 #define XLAT_VAL_1 ((unsigned) (LANDLOCK_RESTRICT_SELF_LOG_NEW_EXEC_ON))
 #define XLAT_STR_1 STRINGIFY(LANDLOCK_RESTRICT_SELF_LOG_NEW_EXEC_ON)
 XLAT(LANDLOCK_RESTRICT_SELF_LOG_SUBDOMAINS_OFF),
 #define XLAT_VAL_2 ((unsigned) (LANDLOCK_RESTRICT_SELF_LOG_SUBDOMAINS_OFF))
 #define XLAT_STR_2 STRINGIFY(LANDLOCK_RESTRICT_SELF_LOG_SUBDOMAINS_OFF)
 XLAT(LANDLOCK_RESTRICT_SELF_TSYNC),
 #define XLAT_VAL_3 ((unsigned) (LANDLOCK_RESTRICT_SELF_TSYNC))
 #define XLAT_STR_3 STRINGIFY(LANDLOCK_RESTRICT_SELF_TSYNC)
 XLAT(LANDLOCK_RESTRICT_SELF_NO_NEW_PRIVS),
 #define XLAT_VAL_4 ((unsigned) (LANDLOCK_RESTRICT_SELF_NO_NEW_PRIVS))
 #define XLAT_STR_4 STRINGIFY(LANDLOCK_RESTRICT_SELF_NO_NEW_PRIVS)
};
static
const struct xlat landlock_restrict_self_flags[1] = { {
 .data = landlock_restrict_self_flags_xdata,
 .size = ARRAY_SIZE(landlock_restrict_self_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
