/* Generated by ./src/xlat/gen.sh from ./src/xlat/lbmd_pi_cap_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat lbmd_pi_cap_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data lbmd_pi_cap_flags_xdata[] = {
 XLAT(LBMD_PI_CAP_INTEGRITY),
 #define XLAT_VAL_0 ((unsigned) (LBMD_PI_CAP_INTEGRITY))
 #define XLAT_STR_0 STRINGIFY(LBMD_PI_CAP_INTEGRITY)
 XLAT(LBMD_PI_CAP_REFTAG),
 #define XLAT_VAL_1 ((unsigned) (LBMD_PI_CAP_REFTAG))
 #define XLAT_STR_1 STRINGIFY(LBMD_PI_CAP_REFTAG)
};
static
const struct xlat lbmd_pi_cap_flags[1] = { {
 .data = lbmd_pi_cap_flags_xdata,
 .size = ARRAY_SIZE(lbmd_pi_cap_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
