/* Generated by ./src/xlat/gen.sh from ./src/xlat/lbmd_pi_csum_types.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat lbmd_pi_csum_types in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data lbmd_pi_csum_types_xdata[] = {
 XLAT(LBMD_PI_CSUM_NONE),
 #define XLAT_VAL_0 ((unsigned) (LBMD_PI_CSUM_NONE))
 #define XLAT_STR_0 STRINGIFY(LBMD_PI_CSUM_NONE)
 XLAT(LBMD_PI_CSUM_IP),
 #define XLAT_VAL_1 ((unsigned) (LBMD_PI_CSUM_IP))
 #define XLAT_STR_1 STRINGIFY(LBMD_PI_CSUM_IP)
 XLAT(LBMD_PI_CSUM_CRC16_T10DIF),
 #define XLAT_VAL_2 ((unsigned) (LBMD_PI_CSUM_CRC16_T10DIF))
 #define XLAT_STR_2 STRINGIFY(LBMD_PI_CSUM_CRC16_T10DIF)
 XLAT(LBMD_PI_CSUM_CRC64_NVME),
 #define XLAT_VAL_3 ((unsigned) (LBMD_PI_CSUM_CRC64_NVME))
 #define XLAT_STR_3 STRINGIFY(LBMD_PI_CSUM_CRC64_NVME)
};
static
const struct xlat lbmd_pi_csum_types[1] = { {
 .data = lbmd_pi_csum_types_xdata,
 .size = ARRAY_SIZE(lbmd_pi_csum_types_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
