/* Generated by ./src/xlat/gen.sh from ./src/xlat/listmount_mnt_id.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat listmount_mnt_id in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data listmount_mnt_id_xdata[] = {
 XLAT_TYPE(uint64_t, LSMT_ROOT),
 #define XLAT_VAL_0 ((uint64_t) (LSMT_ROOT))
 #define XLAT_STR_0 STRINGIFY(LSMT_ROOT)
};
static
const struct xlat listmount_mnt_id[1] = { {
 .data = listmount_mnt_id_xdata,
 .size = ARRAY_SIZE(listmount_mnt_id_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
