/* Generated by ./src/xlat/gen.sh from ./src/xlat/nha_op_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#ifndef BIT
# define BIT(nr_)	(1UL << (nr_))
#endif
#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat nha_op_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data nha_op_flags_xdata[] = {
#ifndef BIT
/*
* Workaround a bug in kernel headers that define NHA_OP_FLAG_* constants
* using BIT() macro without providing its definition.
*/
# define BIT(nr_)	(1UL << (nr_))
#endif

 XLAT(NHA_OP_FLAG_DUMP_STATS),
 #define XLAT_VAL_0 ((unsigned) (NHA_OP_FLAG_DUMP_STATS))
 #define XLAT_STR_0 STRINGIFY(NHA_OP_FLAG_DUMP_STATS)
 XLAT(NHA_OP_FLAG_DUMP_HW_STATS),
 #define XLAT_VAL_1 ((unsigned) (NHA_OP_FLAG_DUMP_HW_STATS))
 #define XLAT_STR_1 STRINGIFY(NHA_OP_FLAG_DUMP_HW_STATS)
 XLAT(NHA_OP_FLAG_RESP_GRP_RESVD_0),
 #define XLAT_VAL_2 ((unsigned) (NHA_OP_FLAG_RESP_GRP_RESVD_0))
 #define XLAT_STR_2 STRINGIFY(NHA_OP_FLAG_RESP_GRP_RESVD_0)
};
static
const struct xlat nha_op_flags[1] = { {
 .data = nha_op_flags_xdata,
 .size = ARRAY_SIZE(nha_op_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
