/* Generated by ./src/xlat/gen.sh from ./src/xlat/pidfd_info_mask.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat pidfd_info_mask in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data pidfd_info_mask_xdata[] = {
 XLAT_TYPE(uint64_t, PIDFD_INFO_PID),
 #define XLAT_VAL_0 ((uint64_t) (PIDFD_INFO_PID))
 #define XLAT_STR_0 STRINGIFY(PIDFD_INFO_PID)
 XLAT_TYPE(uint64_t, PIDFD_INFO_CREDS),
 #define XLAT_VAL_1 ((uint64_t) (PIDFD_INFO_CREDS))
 #define XLAT_STR_1 STRINGIFY(PIDFD_INFO_CREDS)
 XLAT_TYPE(uint64_t, PIDFD_INFO_CGROUPID),
 #define XLAT_VAL_2 ((uint64_t) (PIDFD_INFO_CGROUPID))
 #define XLAT_STR_2 STRINGIFY(PIDFD_INFO_CGROUPID)
 XLAT_TYPE(uint64_t, PIDFD_INFO_EXIT),
 #define XLAT_VAL_3 ((uint64_t) (PIDFD_INFO_EXIT))
 #define XLAT_STR_3 STRINGIFY(PIDFD_INFO_EXIT)
 XLAT_TYPE(uint64_t, PIDFD_INFO_COREDUMP),
 #define XLAT_VAL_4 ((uint64_t) (PIDFD_INFO_COREDUMP))
 #define XLAT_STR_4 STRINGIFY(PIDFD_INFO_COREDUMP)
 XLAT_TYPE(uint64_t, PIDFD_INFO_SUPPORTED_MASK),
 #define XLAT_VAL_5 ((uint64_t) (PIDFD_INFO_SUPPORTED_MASK))
 #define XLAT_STR_5 STRINGIFY(PIDFD_INFO_SUPPORTED_MASK)
 XLAT_TYPE(uint64_t, PIDFD_INFO_COREDUMP_SIGNAL),
 #define XLAT_VAL_6 ((uint64_t) (PIDFD_INFO_COREDUMP_SIGNAL))
 #define XLAT_STR_6 STRINGIFY(PIDFD_INFO_COREDUMP_SIGNAL)
 XLAT_TYPE(uint64_t, PIDFD_INFO_COREDUMP_CODE),
 #define XLAT_VAL_7 ((uint64_t) (PIDFD_INFO_COREDUMP_CODE))
 #define XLAT_STR_7 STRINGIFY(PIDFD_INFO_COREDUMP_CODE)
};
static
const struct xlat pidfd_info_mask[1] = { {
 .data = pidfd_info_mask_xdata,
 .size = ARRAY_SIZE(pidfd_info_mask_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
#  ifdef XLAT_VAL_6
  | XLAT_VAL_6
#  endif
#  ifdef XLAT_VAL_7
  | XLAT_VAL_7
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
#  ifdef XLAT_STR_6
  + sizeof(XLAT_STR_6)
#  endif
#  ifdef XLAT_STR_7
  + sizeof(XLAT_STR_7)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
#  undef XLAT_STR_6
#  undef XLAT_VAL_6
#  undef XLAT_STR_7
#  undef XLAT_VAL_7
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
