/* Generated by ./src/xlat/gen.sh from ./src/xlat/pidfd_coredump_mask.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat pidfd_coredump_mask in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data pidfd_coredump_mask_xdata[] = {
 XLAT(PIDFD_COREDUMPED),
 #define XLAT_VAL_0 ((unsigned) (PIDFD_COREDUMPED))
 #define XLAT_STR_0 STRINGIFY(PIDFD_COREDUMPED)
 XLAT(PIDFD_COREDUMP_SKIP),
 #define XLAT_VAL_1 ((unsigned) (PIDFD_COREDUMP_SKIP))
 #define XLAT_STR_1 STRINGIFY(PIDFD_COREDUMP_SKIP)
 XLAT(PIDFD_COREDUMP_USER),
 #define XLAT_VAL_2 ((unsigned) (PIDFD_COREDUMP_USER))
 #define XLAT_STR_2 STRINGIFY(PIDFD_COREDUMP_USER)
 XLAT(PIDFD_COREDUMP_ROOT),
 #define XLAT_VAL_3 ((unsigned) (PIDFD_COREDUMP_ROOT))
 #define XLAT_STR_3 STRINGIFY(PIDFD_COREDUMP_ROOT)
};
static
const struct xlat pidfd_coredump_mask[1] = { {
 .data = pidfd_coredump_mask_xdata,
 .size = ARRAY_SIZE(pidfd_coredump_mask_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
