/* Generated by ./src/xlat/gen.sh from ./src/xlat/pr_riscv_v_states.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(PR_RISCV_V_VSTATE_CTRL_DEFAULT) || (defined(HAVE_DECL_PR_RISCV_V_VSTATE_CTRL_DEFAULT) && HAVE_DECL_PR_RISCV_V_VSTATE_CTRL_DEFAULT)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((PR_RISCV_V_VSTATE_CTRL_DEFAULT) == (0), "PR_RISCV_V_VSTATE_CTRL_DEFAULT != 0");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define PR_RISCV_V_VSTATE_CTRL_DEFAULT 0
#endif
#if defined(PR_RISCV_V_VSTATE_CTRL_OFF) || (defined(HAVE_DECL_PR_RISCV_V_VSTATE_CTRL_OFF) && HAVE_DECL_PR_RISCV_V_VSTATE_CTRL_OFF)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((PR_RISCV_V_VSTATE_CTRL_OFF) == (1), "PR_RISCV_V_VSTATE_CTRL_OFF != 1");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define PR_RISCV_V_VSTATE_CTRL_OFF 1
#endif
#if defined(PR_RISCV_V_VSTATE_CTRL_ON) || (defined(HAVE_DECL_PR_RISCV_V_VSTATE_CTRL_ON) && HAVE_DECL_PR_RISCV_V_VSTATE_CTRL_ON)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((PR_RISCV_V_VSTATE_CTRL_ON) == (2), "PR_RISCV_V_VSTATE_CTRL_ON != 2");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define PR_RISCV_V_VSTATE_CTRL_ON 2
#endif
#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat pr_riscv_v_states in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data pr_riscv_v_states_xdata[] = {
 [PR_RISCV_V_VSTATE_CTRL_DEFAULT] = XLAT(PR_RISCV_V_VSTATE_CTRL_DEFAULT),
 #define XLAT_VAL_0 ((unsigned) (PR_RISCV_V_VSTATE_CTRL_DEFAULT))
 #define XLAT_STR_0 STRINGIFY(PR_RISCV_V_VSTATE_CTRL_DEFAULT)
 [PR_RISCV_V_VSTATE_CTRL_OFF] = XLAT(PR_RISCV_V_VSTATE_CTRL_OFF),
 #define XLAT_VAL_1 ((unsigned) (PR_RISCV_V_VSTATE_CTRL_OFF))
 #define XLAT_STR_1 STRINGIFY(PR_RISCV_V_VSTATE_CTRL_OFF)
 [PR_RISCV_V_VSTATE_CTRL_ON] = XLAT(PR_RISCV_V_VSTATE_CTRL_ON),
 #define XLAT_VAL_2 ((unsigned) (PR_RISCV_V_VSTATE_CTRL_ON))
 #define XLAT_STR_2 STRINGIFY(PR_RISCV_V_VSTATE_CTRL_ON)
};
static
const struct xlat pr_riscv_v_states[1] = { {
 .data = pr_riscv_v_states_xdata,
 .size = ARRAY_SIZE(pr_riscv_v_states_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
