/* Generated by ./src/xlat/gen.sh from ./src/xlat/pr_riscv_icache_flush_scopes.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(PR_RISCV_SCOPE_PER_PROCESS) || (defined(HAVE_DECL_PR_RISCV_SCOPE_PER_PROCESS) && HAVE_DECL_PR_RISCV_SCOPE_PER_PROCESS)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((PR_RISCV_SCOPE_PER_PROCESS) == (0), "PR_RISCV_SCOPE_PER_PROCESS != 0");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define PR_RISCV_SCOPE_PER_PROCESS 0
#endif
#if defined(PR_RISCV_SCOPE_PER_THREAD) || (defined(HAVE_DECL_PR_RISCV_SCOPE_PER_THREAD) && HAVE_DECL_PR_RISCV_SCOPE_PER_THREAD)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((PR_RISCV_SCOPE_PER_THREAD) == (1), "PR_RISCV_SCOPE_PER_THREAD != 1");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define PR_RISCV_SCOPE_PER_THREAD 1
#endif
#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat pr_riscv_icache_flush_scopes in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data pr_riscv_icache_flush_scopes_xdata[] = {
 [PR_RISCV_SCOPE_PER_PROCESS] = XLAT(PR_RISCV_SCOPE_PER_PROCESS),
 #define XLAT_VAL_0 ((unsigned) (PR_RISCV_SCOPE_PER_PROCESS))
 #define XLAT_STR_0 STRINGIFY(PR_RISCV_SCOPE_PER_PROCESS)
 [PR_RISCV_SCOPE_PER_THREAD] = XLAT(PR_RISCV_SCOPE_PER_THREAD),
 #define XLAT_VAL_1 ((unsigned) (PR_RISCV_SCOPE_PER_THREAD))
 #define XLAT_STR_1 STRINGIFY(PR_RISCV_SCOPE_PER_THREAD)
};
static
const struct xlat pr_riscv_icache_flush_scopes[1] = { {
 .data = pr_riscv_icache_flush_scopes_xdata,
 .size = ARRAY_SIZE(pr_riscv_icache_flush_scopes_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
