/* Generated by ./src/xlat/gen.sh from ./src/xlat/rseq_cs_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rseq_cs_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rseq_cs_flags_xdata[] = {
 XLAT(RSEQ_CS_FLAG_NO_RESTART_ON_PREEMPT),
 #define XLAT_VAL_0 ((unsigned) (RSEQ_CS_FLAG_NO_RESTART_ON_PREEMPT))
 #define XLAT_STR_0 STRINGIFY(RSEQ_CS_FLAG_NO_RESTART_ON_PREEMPT)
 XLAT(RSEQ_CS_FLAG_NO_RESTART_ON_SIGNAL),
 #define XLAT_VAL_1 ((unsigned) (RSEQ_CS_FLAG_NO_RESTART_ON_SIGNAL))
 #define XLAT_STR_1 STRINGIFY(RSEQ_CS_FLAG_NO_RESTART_ON_SIGNAL)
 XLAT(RSEQ_CS_FLAG_NO_RESTART_ON_MIGRATE),
 #define XLAT_VAL_2 ((unsigned) (RSEQ_CS_FLAG_NO_RESTART_ON_MIGRATE))
 #define XLAT_STR_2 STRINGIFY(RSEQ_CS_FLAG_NO_RESTART_ON_MIGRATE)
 XLAT(RSEQ_CS_FLAG_SLICE_EXT_AVAILABLE),
 #define XLAT_VAL_3 ((unsigned) (RSEQ_CS_FLAG_SLICE_EXT_AVAILABLE))
 #define XLAT_STR_3 STRINGIFY(RSEQ_CS_FLAG_SLICE_EXT_AVAILABLE)
 XLAT(RSEQ_CS_FLAG_SLICE_EXT_ENABLED),
 #define XLAT_VAL_4 ((unsigned) (RSEQ_CS_FLAG_SLICE_EXT_ENABLED))
 #define XLAT_STR_4 STRINGIFY(RSEQ_CS_FLAG_SLICE_EXT_ENABLED)
};
static
const struct xlat rseq_cs_flags[1] = { {
 .data = rseq_cs_flags_xdata,
 .size = ARRAY_SIZE(rseq_cs_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
