/* Generated by ./src/xlat/gen.sh from ./src/xlat/rseq_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rseq_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rseq_flags_xdata[] = {
 XLAT(RSEQ_FLAG_UNREGISTER),
 #define XLAT_VAL_0 ((unsigned) (RSEQ_FLAG_UNREGISTER))
 #define XLAT_STR_0 STRINGIFY(RSEQ_FLAG_UNREGISTER)
 XLAT(RSEQ_FLAG_SLICE_EXT_DEFAULT_ON),
 #define XLAT_VAL_1 ((unsigned) (RSEQ_FLAG_SLICE_EXT_DEFAULT_ON))
 #define XLAT_STR_1 STRINGIFY(RSEQ_FLAG_SLICE_EXT_DEFAULT_ON)
};
static
const struct xlat rseq_flags[1] = { {
 .data = rseq_flags_xdata,
 .size = ARRAY_SIZE(rseq_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
