/* Generated by ./src/xlat/gen.sh from ./src/xlat/rt_del_reason.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rt_del_reason in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rt_del_reason_xdata[] = {
 [RT_DEL_REASON_UNSPEC] = XLAT(RT_DEL_REASON_UNSPEC),
 #define XLAT_VAL_0 ((unsigned) (RT_DEL_REASON_UNSPEC))
 #define XLAT_STR_0 STRINGIFY(RT_DEL_REASON_UNSPEC)
 [RT_DEL_REASON_EXPIRED] = XLAT(RT_DEL_REASON_EXPIRED),
 #define XLAT_VAL_1 ((unsigned) (RT_DEL_REASON_EXPIRED))
 #define XLAT_STR_1 STRINGIFY(RT_DEL_REASON_EXPIRED)
 [RT_DEL_REASON_RA_WITHDRAWN] = XLAT(RT_DEL_REASON_RA_WITHDRAWN),
 #define XLAT_VAL_2 ((unsigned) (RT_DEL_REASON_RA_WITHDRAWN))
 #define XLAT_STR_2 STRINGIFY(RT_DEL_REASON_RA_WITHDRAWN)
};
static
const struct xlat rt_del_reason[1] = { {
 .data = rt_del_reason_xdata,
 .size = ARRAY_SIZE(rt_del_reason_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
