/* Generated by ./src/xlat/gen.sh from ./src/xlat/rtnl_br_stp_mode.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rtnl_br_stp_mode in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rtnl_br_stp_mode_xdata[] = {
 [BR_STP_MODE_AUTO] = XLAT(BR_STP_MODE_AUTO),
 #define XLAT_VAL_0 ((unsigned) (BR_STP_MODE_AUTO))
 #define XLAT_STR_0 STRINGIFY(BR_STP_MODE_AUTO)
 [BR_STP_MODE_USER] = XLAT(BR_STP_MODE_USER),
 #define XLAT_VAL_1 ((unsigned) (BR_STP_MODE_USER))
 #define XLAT_STR_1 STRINGIFY(BR_STP_MODE_USER)
 [BR_STP_MODE_KERNEL] = XLAT(BR_STP_MODE_KERNEL),
 #define XLAT_VAL_2 ((unsigned) (BR_STP_MODE_KERNEL))
 #define XLAT_STR_2 STRINGIFY(BR_STP_MODE_KERNEL)
};
static
const struct xlat rtnl_br_stp_mode[1] = { {
 .data = rtnl_br_stp_mode_xdata,
 .size = ARRAY_SIZE(rtnl_br_stp_mode_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
