/* Generated by ./src/xlat/gen.sh from ./src/xlat/rtnl_nha_group_stats_attrs.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rtnl_nha_group_stats_attrs in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rtnl_nha_group_stats_attrs_xdata[] = {
 [NHA_GROUP_STATS_UNSPEC] = XLAT(NHA_GROUP_STATS_UNSPEC),
 #define XLAT_VAL_0 ((unsigned) (NHA_GROUP_STATS_UNSPEC))
 #define XLAT_STR_0 STRINGIFY(NHA_GROUP_STATS_UNSPEC)
 [NHA_GROUP_STATS_ENTRY] = XLAT(NHA_GROUP_STATS_ENTRY),
 #define XLAT_VAL_1 ((unsigned) (NHA_GROUP_STATS_ENTRY))
 #define XLAT_STR_1 STRINGIFY(NHA_GROUP_STATS_ENTRY)
};
static
const struct xlat rtnl_nha_group_stats_attrs[1] = { {
 .data = rtnl_nha_group_stats_attrs_xdata,
 .size = ARRAY_SIZE(rtnl_nha_group_stats_attrs_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
