/* Generated by ./src/xlat/gen.sh from ./src/xlat/rtnl_nha_group_stats_entry_attrs.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rtnl_nha_group_stats_entry_attrs in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rtnl_nha_group_stats_entry_attrs_xdata[] = {
 [NHA_GROUP_STATS_ENTRY_UNSPEC] = XLAT(NHA_GROUP_STATS_ENTRY_UNSPEC),
 #define XLAT_VAL_0 ((unsigned) (NHA_GROUP_STATS_ENTRY_UNSPEC))
 #define XLAT_STR_0 STRINGIFY(NHA_GROUP_STATS_ENTRY_UNSPEC)
 [NHA_GROUP_STATS_ENTRY_ID] = XLAT(NHA_GROUP_STATS_ENTRY_ID),
 #define XLAT_VAL_1 ((unsigned) (NHA_GROUP_STATS_ENTRY_ID))
 #define XLAT_STR_1 STRINGIFY(NHA_GROUP_STATS_ENTRY_ID)
 [NHA_GROUP_STATS_ENTRY_PACKETS] = XLAT(NHA_GROUP_STATS_ENTRY_PACKETS),
 #define XLAT_VAL_2 ((unsigned) (NHA_GROUP_STATS_ENTRY_PACKETS))
 #define XLAT_STR_2 STRINGIFY(NHA_GROUP_STATS_ENTRY_PACKETS)
 [NHA_GROUP_STATS_ENTRY_PACKETS_HW] = XLAT(NHA_GROUP_STATS_ENTRY_PACKETS_HW),
 #define XLAT_VAL_3 ((unsigned) (NHA_GROUP_STATS_ENTRY_PACKETS_HW))
 #define XLAT_STR_3 STRINGIFY(NHA_GROUP_STATS_ENTRY_PACKETS_HW)
};
static
const struct xlat rtnl_nha_group_stats_entry_attrs[1] = { {
 .data = rtnl_nha_group_stats_entry_attrs_xdata,
 .size = ARRAY_SIZE(rtnl_nha_group_stats_entry_attrs_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
