/* Generated by ./src/xlat/gen.sh from ./src/xlat/rwh_write_life_hints.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat rwh_write_life_hints in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data rwh_write_life_hints_xdata[] = {
 XLAT(RWH_WRITE_LIFE_NOT_SET),
 #define XLAT_VAL_0 ((unsigned) (RWH_WRITE_LIFE_NOT_SET))
 #define XLAT_STR_0 STRINGIFY(RWH_WRITE_LIFE_NOT_SET)
 XLAT(RWH_WRITE_LIFE_NONE),
 #define XLAT_VAL_1 ((unsigned) (RWH_WRITE_LIFE_NONE))
 #define XLAT_STR_1 STRINGIFY(RWH_WRITE_LIFE_NONE)
 XLAT(RWH_WRITE_LIFE_SHORT),
 #define XLAT_VAL_2 ((unsigned) (RWH_WRITE_LIFE_SHORT))
 #define XLAT_STR_2 STRINGIFY(RWH_WRITE_LIFE_SHORT)
 XLAT(RWH_WRITE_LIFE_MEDIUM),
 #define XLAT_VAL_3 ((unsigned) (RWH_WRITE_LIFE_MEDIUM))
 #define XLAT_STR_3 STRINGIFY(RWH_WRITE_LIFE_MEDIUM)
 XLAT(RWH_WRITE_LIFE_LONG),
 #define XLAT_VAL_4 ((unsigned) (RWH_WRITE_LIFE_LONG))
 #define XLAT_STR_4 STRINGIFY(RWH_WRITE_LIFE_LONG)
 XLAT(RWH_WRITE_LIFE_EXTREME),
 #define XLAT_VAL_5 ((unsigned) (RWH_WRITE_LIFE_EXTREME))
 #define XLAT_STR_5 STRINGIFY(RWH_WRITE_LIFE_EXTREME)
};
static
const struct xlat rwh_write_life_hints[1] = { {
 .data = rwh_write_life_hints_xdata,
 .size = ARRAY_SIZE(rwh_write_life_hints_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
