/* Generated by ./src/xlat/gen.sh from ./src/xlat/setsock_options.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined __hppa__
#if defined(SO_ATTACH_FILTER) || (defined(HAVE_DECL_SO_ATTACH_FILTER) && HAVE_DECL_SO_ATTACH_FILTER)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((SO_ATTACH_FILTER) == (16410), "SO_ATTACH_FILTER != 16410");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define SO_ATTACH_FILTER 16410
#endif
#else
#if defined(SO_ATTACH_FILTER) || (defined(HAVE_DECL_SO_ATTACH_FILTER) && HAVE_DECL_SO_ATTACH_FILTER)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((SO_ATTACH_FILTER) == (26), "SO_ATTACH_FILTER != 26");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define SO_ATTACH_FILTER 26
#endif
#endif
#if defined __sparc__
#if defined(SO_DEVMEM_DONTNEED) || (defined(HAVE_DECL_SO_DEVMEM_DONTNEED) && HAVE_DECL_SO_DEVMEM_DONTNEED)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((SO_DEVMEM_DONTNEED) == (89), "SO_DEVMEM_DONTNEED != 89");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define SO_DEVMEM_DONTNEED 89
#endif
#elif defined __hppa__
#if defined(SO_DEVMEM_DONTNEED) || (defined(HAVE_DECL_SO_DEVMEM_DONTNEED) && HAVE_DECL_SO_DEVMEM_DONTNEED)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((SO_DEVMEM_DONTNEED) == (16464), "SO_DEVMEM_DONTNEED != 16464");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define SO_DEVMEM_DONTNEED 16464
#endif
#else
#if defined(SO_DEVMEM_DONTNEED) || (defined(HAVE_DECL_SO_DEVMEM_DONTNEED) && HAVE_DECL_SO_DEVMEM_DONTNEED)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((SO_DEVMEM_DONTNEED) == (80), "SO_DEVMEM_DONTNEED != 80");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define SO_DEVMEM_DONTNEED 80
#endif
#endif
#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat setsock_options in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data setsock_options_xdata[] = {

#if defined __hppa__
 XLAT(SO_ATTACH_FILTER),
 #define XLAT_VAL_0 ((unsigned) (SO_ATTACH_FILTER))
 #define XLAT_STR_0 STRINGIFY(SO_ATTACH_FILTER)
#else
 XLAT(SO_ATTACH_FILTER),
 #define XLAT_VAL_1 ((unsigned) (SO_ATTACH_FILTER))
 #define XLAT_STR_1 STRINGIFY(SO_ATTACH_FILTER)
#endif

#if defined __sparc__
 XLAT(SO_DEVMEM_DONTNEED),
 #define XLAT_VAL_2 ((unsigned) (SO_DEVMEM_DONTNEED))
 #define XLAT_STR_2 STRINGIFY(SO_DEVMEM_DONTNEED)
#elif defined __hppa__
 XLAT(SO_DEVMEM_DONTNEED),
 #define XLAT_VAL_3 ((unsigned) (SO_DEVMEM_DONTNEED))
 #define XLAT_STR_3 STRINGIFY(SO_DEVMEM_DONTNEED)
#else
 XLAT(SO_DEVMEM_DONTNEED),
 #define XLAT_VAL_4 ((unsigned) (SO_DEVMEM_DONTNEED))
 #define XLAT_STR_4 STRINGIFY(SO_DEVMEM_DONTNEED)
#endif
};
static
const struct xlat setsock_options[1] = { {
 .data = setsock_options_xdata,
 .size = ARRAY_SIZE(setsock_options_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
