/* Generated by ./src/xlat/gen.sh from ./src/xlat/tcp_ao_keyf_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat tcp_ao_keyf_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data tcp_ao_keyf_flags_xdata[] = {
 XLAT(TCP_AO_KEYF_IFINDEX),
 #define XLAT_VAL_0 ((unsigned) (TCP_AO_KEYF_IFINDEX))
 #define XLAT_STR_0 STRINGIFY(TCP_AO_KEYF_IFINDEX)
 XLAT(TCP_AO_KEYF_EXCLUDE_OPT),
 #define XLAT_VAL_1 ((unsigned) (TCP_AO_KEYF_EXCLUDE_OPT))
 #define XLAT_STR_1 STRINGIFY(TCP_AO_KEYF_EXCLUDE_OPT)
};
static
const struct xlat tcp_ao_keyf_flags[1] = { {
 .data = tcp_ao_keyf_flags_xdata,
 .size = ARRAY_SIZE(tcp_ao_keyf_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
