/* Generated by ./src/xlat/gen.sh from ./src/xlat/tun_offload_features.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat tun_offload_features in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data tun_offload_features_xdata[] = {
 XLAT(TUN_F_CSUM),
 #define XLAT_VAL_0 ((unsigned) (TUN_F_CSUM))
 #define XLAT_STR_0 STRINGIFY(TUN_F_CSUM)
 XLAT(TUN_F_TSO4),
 #define XLAT_VAL_1 ((unsigned) (TUN_F_TSO4))
 #define XLAT_STR_1 STRINGIFY(TUN_F_TSO4)
 XLAT(TUN_F_TSO6),
 #define XLAT_VAL_2 ((unsigned) (TUN_F_TSO6))
 #define XLAT_STR_2 STRINGIFY(TUN_F_TSO6)
 XLAT(TUN_F_TSO_ECN),
 #define XLAT_VAL_3 ((unsigned) (TUN_F_TSO_ECN))
 #define XLAT_STR_3 STRINGIFY(TUN_F_TSO_ECN)
 XLAT(TUN_F_UFO),
 #define XLAT_VAL_4 ((unsigned) (TUN_F_UFO))
 #define XLAT_STR_4 STRINGIFY(TUN_F_UFO)
 XLAT(TUN_F_USO4),
 #define XLAT_VAL_5 ((unsigned) (TUN_F_USO4))
 #define XLAT_STR_5 STRINGIFY(TUN_F_USO4)
 XLAT(TUN_F_USO6),
 #define XLAT_VAL_6 ((unsigned) (TUN_F_USO6))
 #define XLAT_STR_6 STRINGIFY(TUN_F_USO6)
 XLAT(TUN_F_UDP_TUNNEL_GSO),
 #define XLAT_VAL_7 ((unsigned) (TUN_F_UDP_TUNNEL_GSO))
 #define XLAT_STR_7 STRINGIFY(TUN_F_UDP_TUNNEL_GSO)
 XLAT(TUN_F_UDP_TUNNEL_GSO_CSUM),
 #define XLAT_VAL_8 ((unsigned) (TUN_F_UDP_TUNNEL_GSO_CSUM))
 #define XLAT_STR_8 STRINGIFY(TUN_F_UDP_TUNNEL_GSO_CSUM)
};
static
const struct xlat tun_offload_features[1] = { {
 .data = tun_offload_features_xdata,
 .size = ARRAY_SIZE(tun_offload_features_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
#  ifdef XLAT_VAL_6
  | XLAT_VAL_6
#  endif
#  ifdef XLAT_VAL_7
  | XLAT_VAL_7
#  endif
#  ifdef XLAT_VAL_8
  | XLAT_VAL_8
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
#  ifdef XLAT_STR_6
  + sizeof(XLAT_STR_6)
#  endif
#  ifdef XLAT_STR_7
  + sizeof(XLAT_STR_7)
#  endif
#  ifdef XLAT_STR_8
  + sizeof(XLAT_STR_8)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
#  undef XLAT_STR_6
#  undef XLAT_VAL_6
#  undef XLAT_STR_7
#  undef XLAT_VAL_7
#  undef XLAT_STR_8
#  undef XLAT_VAL_8
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
