/* Generated by ./src/xlat/gen.sh from ./src/xlat/tun_ifr_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat tun_ifr_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data tun_ifr_flags_xdata[] = {
 XLAT(IFF_TUN),
 #define XLAT_VAL_0 ((unsigned) (IFF_TUN))
 #define XLAT_STR_0 STRINGIFY(IFF_TUN)
 XLAT(IFF_TAP),
 #define XLAT_VAL_1 ((unsigned) (IFF_TAP))
 #define XLAT_STR_1 STRINGIFY(IFF_TAP)
 XLAT(IFF_NAPI),
 #define XLAT_VAL_2 ((unsigned) (IFF_NAPI))
 #define XLAT_STR_2 STRINGIFY(IFF_NAPI)
 XLAT(IFF_NAPI_FRAGS),
 #define XLAT_VAL_3 ((unsigned) (IFF_NAPI_FRAGS))
 #define XLAT_STR_3 STRINGIFY(IFF_NAPI_FRAGS)
 XLAT(IFF_NO_CARRIER),
 #define XLAT_VAL_4 ((unsigned) (IFF_NO_CARRIER))
 #define XLAT_STR_4 STRINGIFY(IFF_NO_CARRIER)
 XLAT(IFF_BACKPRESSURE),
 #define XLAT_VAL_5 ((unsigned) (IFF_BACKPRESSURE))
 #define XLAT_STR_5 STRINGIFY(IFF_BACKPRESSURE)
 XLAT(IFF_MULTI_QUEUE),
 #define XLAT_VAL_6 ((unsigned) (IFF_MULTI_QUEUE))
 #define XLAT_STR_6 STRINGIFY(IFF_MULTI_QUEUE)
 XLAT(IFF_ATTACH_QUEUE),
 #define XLAT_VAL_7 ((unsigned) (IFF_ATTACH_QUEUE))
 #define XLAT_STR_7 STRINGIFY(IFF_ATTACH_QUEUE)
 XLAT(IFF_DETACH_QUEUE),
 #define XLAT_VAL_8 ((unsigned) (IFF_DETACH_QUEUE))
 #define XLAT_STR_8 STRINGIFY(IFF_DETACH_QUEUE)
 XLAT(IFF_PERSIST),
 #define XLAT_VAL_9 ((unsigned) (IFF_PERSIST))
 #define XLAT_STR_9 STRINGIFY(IFF_PERSIST)
 XLAT(IFF_NO_PI),
 #define XLAT_VAL_10 ((unsigned) (IFF_NO_PI))
 #define XLAT_STR_10 STRINGIFY(IFF_NO_PI)
 XLAT(IFF_ONE_QUEUE),
 #define XLAT_VAL_11 ((unsigned) (IFF_ONE_QUEUE))
 #define XLAT_STR_11 STRINGIFY(IFF_ONE_QUEUE)
 XLAT(IFF_VNET_HDR),
 #define XLAT_VAL_12 ((unsigned) (IFF_VNET_HDR))
 #define XLAT_STR_12 STRINGIFY(IFF_VNET_HDR)
 XLAT(IFF_TUN_EXCL),
 #define XLAT_VAL_13 ((unsigned) (IFF_TUN_EXCL))
 #define XLAT_STR_13 STRINGIFY(IFF_TUN_EXCL)
};
static
const struct xlat tun_ifr_flags[1] = { {
 .data = tun_ifr_flags_xdata,
 .size = ARRAY_SIZE(tun_ifr_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
#  ifdef XLAT_VAL_6
  | XLAT_VAL_6
#  endif
#  ifdef XLAT_VAL_7
  | XLAT_VAL_7
#  endif
#  ifdef XLAT_VAL_8
  | XLAT_VAL_8
#  endif
#  ifdef XLAT_VAL_9
  | XLAT_VAL_9
#  endif
#  ifdef XLAT_VAL_10
  | XLAT_VAL_10
#  endif
#  ifdef XLAT_VAL_11
  | XLAT_VAL_11
#  endif
#  ifdef XLAT_VAL_12
  | XLAT_VAL_12
#  endif
#  ifdef XLAT_VAL_13
  | XLAT_VAL_13
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
#  ifdef XLAT_STR_6
  + sizeof(XLAT_STR_6)
#  endif
#  ifdef XLAT_STR_7
  + sizeof(XLAT_STR_7)
#  endif
#  ifdef XLAT_STR_8
  + sizeof(XLAT_STR_8)
#  endif
#  ifdef XLAT_STR_9
  + sizeof(XLAT_STR_9)
#  endif
#  ifdef XLAT_STR_10
  + sizeof(XLAT_STR_10)
#  endif
#  ifdef XLAT_STR_11
  + sizeof(XLAT_STR_11)
#  endif
#  ifdef XLAT_STR_12
  + sizeof(XLAT_STR_12)
#  endif
#  ifdef XLAT_STR_13
  + sizeof(XLAT_STR_13)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
#  undef XLAT_STR_6
#  undef XLAT_VAL_6
#  undef XLAT_STR_7
#  undef XLAT_VAL_7
#  undef XLAT_STR_8
#  undef XLAT_VAL_8
#  undef XLAT_STR_9
#  undef XLAT_VAL_9
#  undef XLAT_STR_10
#  undef XLAT_VAL_10
#  undef XLAT_STR_11
#  undef XLAT_VAL_11
#  undef XLAT_STR_12
#  undef XLAT_VAL_12
#  undef XLAT_STR_13
#  undef XLAT_VAL_13
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
