/* Generated by ./src/xlat/gen.sh from ./src/xlat/tun_filter_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat tun_filter_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data tun_filter_flags_xdata[] = {
 XLAT(TUN_FLT_ALLMULTI),
 #define XLAT_VAL_0 ((unsigned) (TUN_FLT_ALLMULTI))
 #define XLAT_STR_0 STRINGIFY(TUN_FLT_ALLMULTI)
};
static
const struct xlat tun_filter_flags[1] = { {
 .data = tun_filter_flags_xdata,
 .size = ARRAY_SIZE(tun_filter_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
