/* Generated by ./src/xlat/gen.sh from ./src/xlat/uring_napi_tracking_strategies.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat uring_napi_tracking_strategies in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data uring_napi_tracking_strategies_xdata[] = {
 [IO_URING_NAPI_TRACKING_DYNAMIC] = XLAT(IO_URING_NAPI_TRACKING_DYNAMIC),
 #define XLAT_VAL_0 ((unsigned) (IO_URING_NAPI_TRACKING_DYNAMIC))
 #define XLAT_STR_0 STRINGIFY(IO_URING_NAPI_TRACKING_DYNAMIC)
 [IO_URING_NAPI_TRACKING_STATIC] = XLAT(IO_URING_NAPI_TRACKING_STATIC),
 #define XLAT_VAL_1 ((unsigned) (IO_URING_NAPI_TRACKING_STATIC))
 #define XLAT_STR_1 STRINGIFY(IO_URING_NAPI_TRACKING_STATIC)
 [IO_URING_NAPI_TRACKING_INACTIVE] = XLAT(IO_URING_NAPI_TRACKING_INACTIVE),
 #define XLAT_VAL_2 ((unsigned) (IO_URING_NAPI_TRACKING_INACTIVE))
 #define XLAT_STR_2 STRINGIFY(IO_URING_NAPI_TRACKING_INACTIVE)
};
static
const struct xlat uring_napi_tracking_strategies[1] = { {
 .data = uring_napi_tracking_strategies_xdata,
 .size = ARRAY_SIZE(uring_napi_tracking_strategies_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
