/* Generated by ./src/xlat/gen.sh from ./src/xlat/uring_accept_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat uring_accept_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data uring_accept_flags_xdata[] = {
 XLAT(IORING_ACCEPT_MULTISHOT),
 #define XLAT_VAL_0 ((unsigned) (IORING_ACCEPT_MULTISHOT))
 #define XLAT_STR_0 STRINGIFY(IORING_ACCEPT_MULTISHOT)
 XLAT(IORING_ACCEPT_DONTWAIT),
 #define XLAT_VAL_1 ((unsigned) (IORING_ACCEPT_DONTWAIT))
 #define XLAT_STR_1 STRINGIFY(IORING_ACCEPT_DONTWAIT)
 XLAT(IORING_ACCEPT_POLL_FIRST),
 #define XLAT_VAL_2 ((unsigned) (IORING_ACCEPT_POLL_FIRST))
 #define XLAT_STR_2 STRINGIFY(IORING_ACCEPT_POLL_FIRST)
};
static
const struct xlat uring_accept_flags[1] = { {
 .data = uring_accept_flags_xdata,
 .size = ARRAY_SIZE(uring_accept_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
