/* Generated by ./src/xlat/gen.sh from ./src/xlat/uring_zcrx_event_types.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat uring_zcrx_event_types in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data uring_zcrx_event_types_xdata[] = {
 [ZCRX_EVENT_ALLOC_FAIL] = XLAT(ZCRX_EVENT_ALLOC_FAIL),
 #define XLAT_VAL_0 ((unsigned) (ZCRX_EVENT_ALLOC_FAIL))
 #define XLAT_STR_0 STRINGIFY(ZCRX_EVENT_ALLOC_FAIL)
 [ZCRX_EVENT_COPY] = XLAT(ZCRX_EVENT_COPY),
 #define XLAT_VAL_1 ((unsigned) (ZCRX_EVENT_COPY))
 #define XLAT_STR_1 STRINGIFY(ZCRX_EVENT_COPY)
};
static
const struct xlat uring_zcrx_event_types[1] = { {
 .data = uring_zcrx_event_types_xdata,
 .size = ARRAY_SIZE(uring_zcrx_event_types_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
