/* Generated by ./src/xlat/gen.sh from ./src/xlat/uring_async_cancel_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat uring_async_cancel_flags in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data uring_async_cancel_flags_xdata[] = {
 XLAT(IORING_ASYNC_CANCEL_ALL),
 #define XLAT_VAL_0 ((unsigned) (IORING_ASYNC_CANCEL_ALL))
 #define XLAT_STR_0 STRINGIFY(IORING_ASYNC_CANCEL_ALL)
 XLAT(IORING_ASYNC_CANCEL_FD),
 #define XLAT_VAL_1 ((unsigned) (IORING_ASYNC_CANCEL_FD))
 #define XLAT_STR_1 STRINGIFY(IORING_ASYNC_CANCEL_FD)
 XLAT(IORING_ASYNC_CANCEL_ANY),
 #define XLAT_VAL_2 ((unsigned) (IORING_ASYNC_CANCEL_ANY))
 #define XLAT_STR_2 STRINGIFY(IORING_ASYNC_CANCEL_ANY)
 XLAT(IORING_ASYNC_CANCEL_FD_FIXED),
 #define XLAT_VAL_3 ((unsigned) (IORING_ASYNC_CANCEL_FD_FIXED))
 #define XLAT_STR_3 STRINGIFY(IORING_ASYNC_CANCEL_FD_FIXED)
 XLAT(IORING_ASYNC_CANCEL_USERDATA),
 #define XLAT_VAL_4 ((unsigned) (IORING_ASYNC_CANCEL_USERDATA))
 #define XLAT_STR_4 STRINGIFY(IORING_ASYNC_CANCEL_USERDATA)
 XLAT(IORING_ASYNC_CANCEL_OP),
 #define XLAT_VAL_5 ((unsigned) (IORING_ASYNC_CANCEL_OP))
 #define XLAT_STR_5 STRINGIFY(IORING_ASYNC_CANCEL_OP)
};
static
const struct xlat uring_async_cancel_flags[1] = { {
 .data = uring_async_cancel_flags_xdata,
 .size = ARRAY_SIZE(uring_async_cancel_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
#  ifdef XLAT_VAL_4
  | XLAT_VAL_4
#  endif
#  ifdef XLAT_VAL_5
  | XLAT_VAL_5
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
#  ifdef XLAT_STR_4
  + sizeof(XLAT_STR_4)
#  endif
#  ifdef XLAT_STR_5
  + sizeof(XLAT_STR_5)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
#  undef XLAT_STR_4
#  undef XLAT_VAL_4
#  undef XLAT_STR_5
#  undef XLAT_VAL_5
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
