/* Generated by ./src/xlat/gen.sh from ./src/xlat/uring_napi_ops.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat uring_napi_ops in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data uring_napi_ops_xdata[] = {
 [IO_URING_NAPI_REGISTER_OP] = XLAT(IO_URING_NAPI_REGISTER_OP),
 #define XLAT_VAL_0 ((unsigned) (IO_URING_NAPI_REGISTER_OP))
 #define XLAT_STR_0 STRINGIFY(IO_URING_NAPI_REGISTER_OP)
 [IO_URING_NAPI_STATIC_ADD_ID] = XLAT(IO_URING_NAPI_STATIC_ADD_ID),
 #define XLAT_VAL_1 ((unsigned) (IO_URING_NAPI_STATIC_ADD_ID))
 #define XLAT_STR_1 STRINGIFY(IO_URING_NAPI_STATIC_ADD_ID)
 [IO_URING_NAPI_STATIC_DEL_ID] = XLAT(IO_URING_NAPI_STATIC_DEL_ID),
 #define XLAT_VAL_2 ((unsigned) (IO_URING_NAPI_STATIC_DEL_ID))
 #define XLAT_STR_2 STRINGIFY(IO_URING_NAPI_STATIC_DEL_ID)
};
static
const struct xlat uring_napi_ops[1] = { {
 .data = uring_napi_ops_xdata,
 .size = ARRAY_SIZE(uring_napi_ops_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
