name: Build native and with the NDK
on:
  push:
    branches:
      - fixes
  workflow_dispatch:
  workflow_call:
jobs:
  autoreconf:
    uses: turistu/odds-n-ends/.github/workflows/auto.yml@main
    with:
      cmd: ./bootstrap
    permissions:
      contents: write
  build-with-ndk:
    needs: autoreconf
    uses: turistu/odds-n-ends/.github/workflows/build-with-ndk.yml@main
    with:
      build: .github/build-with-ndk
      ref: ${{github.ref_name}}-auto
  build-native:
    needs: autoreconf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}-auto
      - run: sudo apt-get install gcc-multilib
      - run: ./configure
      - run: make
      # - run: make check
  sync-for-upstream:
    needs: [build-with-ndk, build-native]
    uses: turistu/odds-n-ends/.github/workflows/sync.yml@main
    secrets: inherit
    with:
      branch: for-upstream
      upstream: https://github.com/strace/strace
    permissions:
      contents: write
